"""created a one to many relationship

Revision ID: 67c4d5291878
Revises: 9a10886f0348
Create Date: 2018-04-26 12:05:11.310932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c4d5291878'
down_revision = '9a10886f0348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'joiner_id')
    op.add_column('users', sa.Column('joiner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'events', ['joiner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'joiner_id')
    op.add_column('events', sa.Column('joiner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
