"""changed column name

Revision ID: ae4e8f523814
Revises: 67c4d5291878
Create Date: 2018-04-26 12:24:59.370266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae4e8f523814'
down_revision = '67c4d5291878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('event_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_joiner_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'events', ['event_id'], ['id'])
    op.drop_column('users', 'joiner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('joiner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_joiner_id_fkey', 'users', 'events', ['joiner_id'], ['id'])
    op.drop_column('users', 'event_id')
    # ### end Alembic commands ###
